---
- name: Create the file repository configuration
  ansible.builtin.shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  args:
    creates: /etc/apt/sources.list.d/pgdg.list
  when: ansible_os_family == 'Debian'

- name: Import the repository signing key
  ansible.builtin.shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Update apt repo and cache on all Debian
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Install postgres for RedHat
  ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install PostgreSQL
  ansible.builtin.package:
    name: 'postgresql-{{ postgres_version }}'
    state: present

- name: Start PostgreSQL 14
  ansible.builtin.systemd:
    name: 'postgresql@{{ postgres_version }}-main.service'
    enabled: yes
    state: started

- name: Allow PG local access
  community.postgresql.postgresql_pg_hba:
    dest: '/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf'
    contype: host
    users: all
    databases: '{{ db_name }}'
    method: md5
    source: 127.0.0.1/32
  notify: Restart PostgreSQL service

#
#   Avoid error semctl(SETVAL)
#
- name: Fix Logind
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^RemoveIPC='
    insertafter: '^#RemoveIPC=yes$'
    line: 'RemoveIPC=no'

- name: Change default password
  ansible.builtin.shell: psql -c "ALTER ROLE postgres WITH PASSWORD '{{ db_system }}'"
  become: true
  become_user: postgres
  changed_when: false